---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: frontend
  labels:
    app: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: amolsontakke96/mern-frontend:latest   # <-- change to your image
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "http://node-backend.backend.svc.cluster.local:4000"

---
apiVersion: v1
kind: Service
metadata:
  namespace: frontend
  name: react-frontend
  labels:
    app: react-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: react-frontend
