apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  labels:
    app: node-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
        - name: node-backend
          image:  amolsontakke96/back-end:latest   # <-- replace with your Docker image
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: MONGO_URI
              value: "mongodb://mernuser:mernpass@mongo-service:27017/mernDB"   # <-- your MongoDB service name

---
apiVersion: v1
kind: Service
metadata:
  name: node-backend
  labels:
    app: node-backend
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: node-backend


