vpc_name = "T-rex-vpc"
vpc_cidr_block = "10.0.0.0/16"
T-rex-public-subnet-availability-zone-1a-name = "T-rex-public-subnet-1a"
T-rex-public-subnet-availability-zone-1a = "us-east-1a"
T-rex-public-subnet-availability-zone-1a-cidr-block = "10.0.1.0/24"
T-rex-private-subnet-availability-zone-1a-name = "T-rex-private-subnet-1a"
T-rex-private-subnet-availability-zone-1a = "us-east-1a"
T-rex-private-subnet-availability-zone-1a-cidr-block = "10.0.2.0/24"
T-rex-public-subnet-availability-zone-1b-name = "T-rex-public-subnet-1b"
T-rex-public-subnet-availability-zone-1b = "us-east-1b"
T-rex-public-subnet-availability-zone-1b-cidr-block = "10.0.3.0/24"
T-rex-private-subnet-availability-zone-1b-name = "T-rex-private-subnet-1b"
T-rex-private-subnet-availability-zone-1b = "us-east-1b"
T-rex-private-subnet-availability-zone-1b-cidr-block = "10.0.4.0/24"
T-rex-igw-name = "T-rex-igw"
T-rex-elastic-ip-domain = "vpc"
T-rex-elastic-ip-name = "T-rex-eip"
T-rex-public-rt-name = "T-rex-public-rt"
T-rex-public-route-destination_cidr_block = "0.0.0.0/0"
T-rex-private-rt-name = "T-rex-private-rt"
T-rex-private-route-destination_cidr_block = "0.0.0.0/0"
T-rex-nat-gateway-name = "T-rex-nat-gateway"
security_group_name = "T-rex-sg"
security_group_description = "Security group for T-rex VPC"
security_group_tag_name = "T-rex-sg"
security_group_ingress_cidr_ipv4 = "0.0.0.0/0"
security_group_ingress_protocol = "-1"
security_group_egress_cidr_ipv4 = "0.0.0.0/0"
security_group_egress_protocol = "-1"


#eks
demo-eks-cluster-role-name = "demo-eks-cluster-role"
demo-eks-cluster-name = "demo-eks-cluster"
endpoint_private_access = true
endpoint_public_access = true
cluster_verison = "1.33"
support_type = "STANDARD"
authentication_mode = "API"
bootstrap_cluster_creator_admin_permissions = true
bootstrap_self_managed_addons = true
demo-eks-farget-profile-role = "demo-eks-farget-profile-role"
demo-eks-farget-profile = "demo-eks-farget-profile"
selector-namespace = [ "default", "kube-system" ]
eks-node-group-role = "demo-eks-node-group-role"
eks-node-group = "demo-eks-node-group"
desired_size = 1
max_size = 2
min_size = 1
max_unavailable = 1